### ISSUE TITLE
Branch Docker lädt keine Tweets

### ISSUE THREAD

**Issue by Dingensen** [Dingensen/GeoSoft2_Gruppe2#10]
auf commit https://github.com/Dingensen/GeoSoft2_Gruppe2/commit/62190c88605c636002f7ae28c9ef1673e5f499fa im docker-branch lässt sich die App containerisieren, aber beim Zugriff auf die im container laufende App werden keine tweets geladen.

Ursache zur Zeit unbekannt.

**Comment by Dingensen** [comment]
mit commit https://github.com/Dingensen/GeoSoft2_Gruppe2/commit/06b6cd598475e2031600b14c2475121a3673cfe5 besteht jetzt eine gute Verbindung zum mongo-teil der Anwendung.
Es ist nun möglich aus dem web gecachte Daten wie die Unwetterwarnungen abzufragen.

Es werden allerdings keine tweets gecacht.
Beim caching von tweets tritt folgende Fehlermeldung auf:
```
geomergency-app | Error: Status Code: 401
geomergency-app |     at Request.<anonymous> (/usr/src/app/node_modules/twitter/lib/twitter.js:277:28)
geomergency-app |     at Request.emit (events.js:305:20)
geomergency-app |     at Request.onRequestResponse (/usr/src/app/node_modules/request/request.js:1066:10)
geomergency-app |     at ClientRequest.emit (events.js:305:20)
geomergency-app |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
geomergency-app |     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
geomergency-app |     at TLSSocket.socketOnData (_http_client.js:470:22)
geomergency-app |     at TLSSocket.emit (events.js:305:20)
geomergency-app |     at addChunk (_stream_readable.js:341:12)
geomergency-app |     at readableAddChunk (_stream_readable.js:316:11)
geomergency-app |     at TLSSocket.Readable.push (_stream_readable.js:250:10)
geomergency-app |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

Ich halte es für möglich dass der Fehler in der twitter library liegt, aber kann es grade nicht bestätigen

**Comment by Dingensen** [comment]
Status Code: 401 bedeutet dass der request nicht authentifiziert werden konnte.
Vielleicht werden die tokens durch docker irgendwie ungültig..

**Comment by Dingensen** [comment]
verwendung der besser maintainten variation der twitter-package [twitter-lite](url) führt zu dem gleichen Problem.
Die Applikation außerhalb von Docker läuft einwandfrei, innerhalb liefert sie aber folgende Fehlermeldung:
```
geomergency-app | Response {
geomergency-app |   size: 0,
geomergency-app |   timeout: 0,
geomergency-app |   _headers: [Object: null prototype] {
geomergency-app |     'cache-control': [ 'must-revalidate,no-cache,no-store' ],
geomergency-app |     connection: [ 'close' ],
geomergency-app |     'content-encoding': [ 'gzip' ],
geomergency-app |     'content-type': [ 'text/html' ],
geomergency-app |     date: [ 'Sat, 25 Jan 2020 08:22:15 GMT' ],
geomergency-app |     server: [ 'tsa_b' ],
geomergency-app |     'set-cookie': [
geomergency-app |       'personalization_id="v1_c/gfbiP6HtewL2JbCX+pSA=="; Max-Age=63072000; Expires=Mon, 24 Jan 2022 08:22:15 GMT; Path=/; Domain=.twitter.com',
geomergency-app |       'guest_id=v1%3A157994053522427417; Max-Age=63072000; Expires=Mon, 24 Jan 2022 08:22:15 GMT; Path=/; Domain=.twitter.com'
geomergency-app |     ],
geomergency-app |     'strict-transport-security': [ 'max-age=631138519' ],
geomergency-app |     'transfer-encoding': [ 'chunked' ],
geomergency-app |     'www-authenticate': [ 'OAuth realm="Firehose"' ],
geomergency-app |     'x-connection-hash': [ '416dae96a455e3fef869c48d5d167264' ],
geomergency-app |     'x-response-time': [ '12' ],
geomergency-app |     'x-tsa-request-body-time': [ '1' ],
geomergency-app |     'x-xss-protection': [ '0' ]
geomergency-app |   },
geomergency-app |   [Symbol(Body internals)]: {
geomergency-app |     body: Gunzip {
geomergency-app |       _writeState: [Uint32Array],
geomergency-app |       _readableState: [ReadableState],
geomergency-app |       readable: true,
geomergency-app |       _events: [Object: null prototype],
geomergency-app |       _eventsCount: 6,
geomergency-app |       _maxListeners: undefined,
geomergency-app |       _writableState: [WritableState],
geomergency-app |       writable: true,
geomergency-app |       allowHalfOpen: true,
geomergency-app |       _transformState: [Object],
geomergency-app |       _hadError: false,
geomergency-app |       bytesWritten: 0,
geomergency-app |       _handle: [Zlib],
geomergency-app |       _outBuffer: <Buffer 68 32 fa a4 d5 7f 00 00 d0 61 1d 05 00 00 00 00 d0 61 1d 05 00 00 00 00 d0 61 1d 05 00 00 00 00 08 00 00 00 00 00 00 00 50 58 31 05 00 00 00 00 c8 3e ... 16334 more bytes>,
geomergency-app |       _outOffset: 0,
geomergency-app |       _chunkSize: 16384,
geomergency-app |       _defaultFlushFlag: 2,
geomergency-app |       _finishFlushFlag: 2,
geomergency-app |       _defaultFullFlushFlag: 3,
geomergency-app |       _info: undefined,
geomergency-app |       _level: -1,
geomergency-app |       _strategy: 0,
geomergency-app |       [Symbol(kCapture)]: false
geomergency-app |     },
geomergency-app |     disturbed: false,
geomergency-app |     error: null
geomergency-app |   },
geomergency-app |   [Symbol(Response internals)]: {
geomergency-app |     url: 'https://stream.twitter.com/1.1/statuses/filter.json',
geomergency-app |     status: 401,
geomergency-app |     statusText: 'Authorization Required',
geomergency-app |     headers: Headers { [Symbol(map)]: [Object: null prototype] },
geomergency-app |     counter: 0
geomergency-app |   }
geomergency-app | }
```

**Comment by Dingensen** [comment]
beim einsehen der keys im client-object, welches den stream initialisiert zeigt sich auch dass die keys in der dockerisierten version und in der nackten node-version die selben sind:

docker:
```
geomergency-app |   headers: {
geomergency-app |     Accept: '*/*',
geomergency-app |     Connection: 'close',
geomergency-app |     'User-Agent': 'node-twitter/1.7.1'
geomergency-app |   },
geomergency-app |   oauth: {
geomergency-app |     consumer_key: 'M2ZR[...]Rbsm',
geomergency-app |     consumer_secret: 'Bx7i[...]F4AF',
geomergency-app |     token: '1198[...]88Ao',
geomergency-app |     token_secret: 'LleR[...]v9Ux'
geomergency-app |   }
geomergency-app | }
```

nicht-docker:
```
{ headers:
   { Accept: '*/*',
     Connection: 'close',
     'User-Agent': 'node-twitter/1.7.1' },
  oauth:
   { consumer_key: 'M2ZR[...]Rbsm',
     consumer_secret: 'Bx7i[...]F4AF',
     token: '1198[...]88Ao',
     token_secret: 'LleR[...]v9Ux' } }
```

**Comment by Dingensen** [comment]
auch verwendung der library [twitter-stream-api](url) gibt einen 401 error in docker, klappt aber außerhalb.

```
geomergency-app | connection error http 401
```

**Comment by Dingensen** [comment]
Verwendung der [twit](https://github.com/ttezel/twit)-library funktioniert ebenso im nicht-docker environment, nicht aber im docker-container:

```
geomergency-app | events.js:282
geomergency-app |       throw er; // Unhandled 'error' event
geomergency-app |       ^
geomergency-app |
geomergency-app | Error: Bad Twitter streaming request: 401
geomergency-app |     at Object.exports.makeTwitError (/usr/src/app/node_modules/twit/lib/helpers.js:74:13)
geomergency-app |     at Request.<anonymous> (/usr/src/app/node_modules/twit/lib/streaming-api-connection.js:96:29)
geomergency-app |     at Request.emit (events.js:317:22)
geomergency-app |     at Gunzip.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
geomergency-app |     at Object.onceWrapper (events.js:411:28)
geomergency-app |     at Gunzip.emit (events.js:317:22)
geomergency-app |     at endReadableNT (_stream_readable.js:1215:12)
geomergency-app |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
geomergency-app | Emitted 'error' event on StreamingAPIConnection instance at:
geomergency-app |     at Request.<anonymous> (/usr/src/app/node_modules/twit/lib/streaming-api-connection.js:99:14)
geomergency-app |     at Request.emit (events.js:317:22)
geomergency-app |     [... lines matching original stack trace ...]
geomergency-app |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
geomergency-app |   message: 'Bad Twitter streaming request: 401',
geomergency-app |   code: null,
geomergency-app |   allErrors: [],
geomergency-app |   twitterReply: '<html>\\n<head>\\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\\n<title>Error 401 Unauthorized</title>\n' +
geomergency-app |     '</head>\n' +
geomergency-app |     '<body>\n' +
geomergency-app |     '<h2>HTTP ERROR: 401</h2>\n' +
geomergency-app |     "<p>Problem accessing '/1.1/statuses/filter.json'. Reason:\n" +
geomergency-app |     '<pre>    Unauthorized</pre>\n' +
geomergency-app |     '</body>\n' +
geomergency-app |     '</html>\n',
geomergency-app |   statusCode: 401
geomergency-app | }
```

**Comment by nuest** [comment]
Auf den ersten Blick habe ich keine Idee was hier falsch laufen könnte, konnte das Problem aber auch lokal nicht hervorrufen:

- Bitte im Branch `docker` eine Anleitung ergänzen, wie ihr die app startet (Ich schätze irgendwas mit `docker-compose`...), sonst kann ich das nicht exact nachvollziehen. Dazu gehört auch welche URL ich eingeben muss, damit der Fehler kommt.
- Bitte eine Anleitung ergänzen wo ich consumer key und access token etc. her bekomme - der Vollständigkeit halber, und damit ich nicht eine andere Anleitung befolge als ihr genutzt habt.
- Der Sicherheit halber solltet ihr _nie_ Tokens im container speichern, sondern immer nur hinein mounten, also über Umgebungsvariablen oder die `tokens.js` zur Laufzeit hinein mounten.

**Comment by Dingensen** [comment]
@nuest danke für die Hilfeleistung.
Aus unerklärten Gründen funktioniert die Applikation nun sinngemäß innerhalb Docker.
Ich schließe das issue vorerst, aber es kann wieder geöffnet werden, sollte das Problem erneut auftreten.

**Comment by Dingensen** [comment]
update: das Problem ist erneut kurzzeitig aufgetreten.

Ich habe den computer aus dem Hibernation-mode hochgefahren (was meines wissens auch der Fall war als dieser Fehler zuletzt aufgetreten ist), laufende container gestoppt, mit `docker container prune`  alle container entfernt, und anschließend wieder mit
`docker build -t geomergency-app .`
den container gebaut, und dann mit
`docker-compose up` die container gestartet. Das ergebnis war ein 401-Error wie im zweitem kommentar dieses issues.
Danach habe ich den computer neu gestartet, die container diesmal nicht ge-pruned, und wieder mit der gleichen vorgehensweise die container initialisiert. Da hat es wieder funktioniert.

Ich vermute stark dass der windows-hibernation-modus den Fehler verursacht, aufgrund der inkonsistenten vorgehensweise mit prune kann ich aber nichts mit Sicherheit sagen.
